"""
FinSight Pydantic Request & Response Schemas
=============================================
"""

from typing import Any, Dict, Optional
from pydantic import BaseModel, Field


class AskRequest(BaseModel):
    """Request schema for the conversational AI /ask endpoint."""

    user_id: str = Field(
        default="demo_user",
        description="The authenticated user identifier.",
        examples=["demo_user"],
    )
    query: str = Field(
        ...,
        description="The user's natural language financial inquiry.",
        examples=["What's my balance?", "Can I afford headphones for 8k?"],
    )
    context: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional application or conversational context.",
    )


class AskResponse(BaseModel):
    """Response schema for the conversational AI /ask endpoint."""

    answer_text: str = Field(
        ...,
        description="Grounded, natural-language explanation generated by the explainer.",
    )
    structured_data: Any = Field(
        ...,
        description="Authoritative structured financial facts from the deterministic engine, or clarification/error details.",
    )
